import { type RouteConfig, index, route } from "@react-router/dev/routes";

export default [
    index("routes/home.tsx"),
    route("auth", "routes/auth.tsx"),
    route("property/:id", "routes/property.tsx"),
    route("book/:id", "routes/book.tsx"),
    route("operator", "routes/operator.dashboard.tsx"),
    route("host/edit/:id", "routes/admin.edit.tsx"),
    route("admin/tokenize/:listingId", "routes/admin.tokenize.tsx"),
    route("admin", "routes/admin.dashboard.tsx"),
    route("admin/settlements", "routes/admin.settlements.tsx"),
    route("admin/settlements/:listingId", "routes/admin.settlements.detail.tsx"),
    route("auth/*", "routes/auth.$.tsx"),
    route("api/sign-cloudinary", "routes/api.sign-cloudinary.ts"),
    route("api/rwa/save-mint", "routes/api.rwa.save-mint.ts"),
    route("api/rwa/record-purchase", "routes/api.rwa.record-purchase.ts"),
    route("api/rwa/activate", "routes/api.rwa.activate.ts"),
    route("api/rwa/claim-dividend", "routes/api.rwa.claim-dividend.ts"),
    route("api/rwa/refund", "routes/api.rwa.refund.ts"),
    route("api/rwa/my-investment", "routes/api.rwa.my-investment.ts"),
    route("api/rwa/release-funds", "routes/api.rwa.release-funds.ts"),
    route("api/rwa/distribute-dividend", "routes/api.rwa.distribute-dividend.ts"),
    route("api/rwa/cancel-position", "routes/api.rwa.cancel-position.ts"),
    route("api/operator/distribute-settlement", "routes/api.operator.distribute-settlement.ts"),
    route("api/operator/claim-settlement", "routes/api.operator.claim-settlement.ts"),
    route("api/admin/monthly-settlement", "routes/api.admin.monthly-settlement.ts"),
    route("api/chat/concierge", "routes/api.chat.concierge.ts"),
    route("api/user/kyc-status", "routes/api.user.kyc-status.ts"),
    route("api/user/save-kyc", "routes/api.user.save-kyc.ts"),
    route("api/user/wallet-nonce", "routes/api.user.wallet-nonce.ts"),
    route("api/user/connect-wallet", "routes/api.user.connect-wallet.ts"),
    route("search", "routes/search.tsx"),
    route("invest", "routes/invest.tsx"),
    route("invest/:listingId", "routes/invest.detail.tsx"),
    route("my-investments", "routes/my-investments.tsx"),
    route("kyc", "routes/kyc.tsx"),

] satisfies RouteConfig;
