import { type RouteConfig, index, route, layout } from "@react-router/dev/routes";

export default [
    index("routes/home.tsx"),
    route("auth", "routes/auth.tsx"),
    route("property/:id", "routes/property.tsx"),
    route("book/:id", "routes/book.tsx"),
    route("operator", "routes/operator.dashboard.tsx"),
    route("host/edit/:id", "routes/admin.edit.tsx"),
    route("api/building/lookup", "routes/api.building.lookup.ts"),
    layout("routes/admin._layout.tsx", [
        route("admin", "routes/admin.dashboard.tsx"),
        route("admin/bookings", "routes/host.bookings.tsx"),
        route("admin/listing/new", "routes/admin.listing.new.tsx"),
        route("admin/tokenize/:listingId", "routes/admin.tokenize.tsx"),
        route("admin/operators", "routes/admin.operators.tsx"),
        route("admin/settlements", "routes/admin.settlements.tsx"),
        route("admin/settlements/:listingId", "routes/admin.settlements.detail.tsx"),
        route("admin/council-token", "routes/admin.council-token.tsx"),
        route("admin/treasury", "routes/admin.treasury.tsx"),
        route("admin/messages/:bookingId", "routes/admin.messages.$bookingId.tsx"),
    ]),
    route("api/auth/session", "routes/api.auth.session.ts"),
    route("api/user/me", "routes/api.user.me.ts"),
    route("api/user/sync-wallet", "routes/api.user.sync-wallet.ts"),
    route("api/sign-cloudinary", "routes/api.sign-cloudinary.ts"),
    route("api/rwa/save-mint", "routes/api.rwa.save-mint.ts"),
    route("api/rwa/record-purchase", "routes/api.rwa.record-purchase.ts"),
    route("api/rwa/activate", "routes/api.rwa.activate.ts"),
    route("api/rwa/claim-dividend", "routes/api.rwa.claim-dividend.ts"),
    route("api/rwa/refund", "routes/api.rwa.refund.ts"),
    route("api/rwa/mark-refunded", "routes/api.rwa.mark-refunded.ts"),
    route("api/rwa/my-investment", "routes/api.rwa.my-investment.ts"),
    route("api/rwa/release-funds", "routes/api.rwa.release-funds.ts"),
    route("api/rwa/distribute-dividend", "routes/api.rwa.distribute-dividend.ts"),
    route("api/rwa/cancel-position", "routes/api.rwa.cancel-position.ts"),
    route("api/rwa/crank-activate", "routes/api.rwa.crank-activate.ts"),
    route("api/operator/distribute-settlement", "routes/api.operator.distribute-settlement.ts"),
    route("api/operator/claim-settlement", "routes/api.operator.claim-settlement.ts"),
    route("api/admin/monthly-settlement", "routes/api.admin.monthly-settlement.ts"),
    route("api/admin/force-fund", "routes/api.admin.force-fund.ts"),
    route("api/admin/issue-council-token", "routes/api.admin.issue-council-token.ts"),
    route("api/admin/create-operator", "routes/api.admin.create-operator.ts"),
    route("api/chat/concierge", "routes/api.chat.concierge.ts"),
    route("api/chat/messages", "routes/api.chat.messages.ts"),
    route("api/set-language", "routes/api.set-language.ts"),
    route("api/governance/issue", "routes/api.governance.issue.ts"),
    route("api/user/kyc-status", "routes/api.user.kyc-status.ts"),
    route("api/user/save-kyc", "routes/api.user.save-kyc.ts"),
    route("api/user/wallet-nonce", "routes/api.user.wallet-nonce.ts"),
    route("api/user/connect-wallet", "routes/api.user.connect-wallet.ts"),
    route("api/paypal/create-order", "routes/api.paypal.create-order.ts"),
    route("api/paypal/capture-auth", "routes/api.paypal.capture-auth.ts"),
    route("api/booking/confirm", "routes/api.booking.confirm.ts"),
    route("api/booking/approve", "routes/api.booking.approve.ts"),
    route("api/booking/reject", "routes/api.booking.reject.ts"),
    route("api/booking/release-escrow", "routes/api.booking.release-escrow.ts"),
    route("api/booking/cancel-confirmed", "routes/api.booking.cancel-confirmed.ts"),
    route("api/cron/release-escrow", "routes/api.cron.release-escrow.ts"),
    route("api/cron/rwa-activate", "routes/api.cron.rwa-activate.ts"),
    route("api/booking/guest-cancel", "routes/api.booking.guest-cancel.ts"),
    route("api/actions/invest/:listingId", "routes/api.actions.invest.$listingId.ts"),
    route("api/actions/governance/:proposalId", "routes/api.actions.governance.$proposalId.ts"),
    route("api/webhooks/helius", "routes/api.webhooks.helius.ts"),
    route("book/success", "routes/book.success.tsx"),
    route("book/fail", "routes/book.fail.tsx"),
    route("search", "routes/search.tsx"),
    route("invest", "routes/invest.tsx"),
    route("invest/:listingId", "routes/invest.detail.tsx"),
    layout("routes/my._layout.tsx", [
        route("my/bookings",               "routes/my.bookings.tsx"),
        route("my/payments",               "routes/my.payments.tsx"),
        route("my/portfolio",              "routes/my.portfolio.tsx"),
        route("my/messages/:bookingId",    "routes/my.messages.$bookingId.tsx"),
    ]),
    // 구 URL → 신 URL 리다이렉트
    route("my-bookings",   "routes/my-bookings.tsx"),
    route("my-investments", "routes/my-investments.tsx"),
    route("host/bookings", "routes/redirect.host-bookings.ts"),
    route("kyc", "routes/kyc.tsx"),
    route("governance", "routes/governance.tsx"),
    route("governance/new", "routes/governance.new.tsx"),
    route("governance/:id", "routes/governance.$id.tsx"),
    route("sitemap.xml", "routes/sitemap[.xml].ts"),
] satisfies RouteConfig;
